- hosts: all
  become: true
  tasks:
    - name: Install Python & Pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
    - name: Install Flask
      pip:
        name: flask
